In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
base = pd.read_csv('iris.csv')

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
#sleciona todas as linhas da coluna 0 a coluna 3
previsores = base.iloc[:, 0:4].values

#seleciona todas as linhas da coluna 4
classe = base.iloc[:,4].values

In [3]:
#transformação de atributos categóricos para atributos numéticos
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
classe = labelEncoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)
#iris setosa     1 0 0
#iris virginica  0 1 0
#iris versicolor 0 0 1

In [4]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)

In [10]:
classificador = Sequential()
#primeira camada oculta com a camada de entrada
classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
#segunda camada oculta
classificador.add(Dense(units = 4, activation = 'relu'))
#camada de saída
classificador.add(Dense(units = 3, activation = 'softmax'))

classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['categorical_accuracy'])

#treinamento da rede
classificador.fit(previsores_treinamento, classe_treinamento, batch_size = 10, epochs = 100)

#teste da rede
resultados = classificador.evaluate(previsores_teste, classe_teste)

#teste para uma instancia
previsoes = classificador.predict(previsores_teste)

previsoes = (previsoes > 0.5)

Epoch 1/100
112/112 [==============================] - 0s 4ms/step - loss: 1.3702 - categorical_accuracy: 0.3036
Epoch 2/100
112/112 [==============================] - 0s 285us/step - loss: 1.3170 - categorical_accuracy: 0.3036
Epoch 3/100
112/112 [==============================] - 0s 250us/step - loss: 1.2759 - categorical_accuracy: 0.3036
Epoch 4/100
112/112 [==============================] - 0s 285us/step - loss: 1.2434 - categorical_accuracy: 0.3036
Epoch 5/100
112/112 [==============================] - 0s 285us/step - loss: 1.2135 - categorical_accuracy: 0.3036
Epoch 6/100
112/112 [==============================] - 0s 285us/step - loss: 1.1858 - categorical_accuracy: 0.3036
Epoch 7/100
112/112 [==============================] - 0s 321us/step - loss: 1.1651 - categorical_accuracy: 0.3036
Epoch 8/100
112/112 [==============================] - 0s 250us/step - loss: 1.1446 - categorical_accuracy: 0.3036
Epoch 9/100
112/112 [==============================] - 0s 214us/step - loss: 1.125

112/112 [==============================] - 0s 214us/step - loss: 0.5765 - categorical_accuracy: 0.9375
Epoch 72/100
112/112 [==============================] - 0s 214us/step - loss: 0.5717 - categorical_accuracy: 0.9375
Epoch 73/100
112/112 [==============================] - 0s 178us/step - loss: 0.5671 - categorical_accuracy: 0.9375
Epoch 74/100
112/112 [==============================] - 0s 178us/step - loss: 0.5626 - categorical_accuracy: 0.9107
Epoch 75/100
112/112 [==============================] - 0s 285us/step - loss: 0.5582 - categorical_accuracy: 0.9107
Epoch 76/100
112/112 [==============================] - 0s 214us/step - loss: 0.5529 - categorical_accuracy: 0.9375
Epoch 77/100
112/112 [==============================] - 0s 214us/step - loss: 0.5489 - categorical_accuracy: 0.9375
Epoch 78/100
112/112 [==============================] - 0s 178us/step - loss: 0.5429 - categorical_accuracy: 0.9464
Epoch 79/100
112/112 [==============================] - 0s 178us/step - loss: 0.5390 

In [13]:
from sklearn.metrics import confusion_matrix
import numpy as np
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

matrix = confusion_matrix(previsoes2, classe_teste2)
print(matrix)

[[ 8  0  0]
 [ 0 13  0]
 [ 0  1 16]]
